import 'package:jellyfin_dart/jellyfin_dart.dart';
import 'package:material_ui/material_ui.dart';

import 'home_scroll.dart';
import 'layout_section.dart';
import 'skin.dart';

/// Skins predefinidos.
abstract final class SkinPresets {
  /// Estilo actual: oscuro azul/púrpura.
  static const Skin jellyfinDefault = Skin(
    id: 'jellyfin_default',
    name: 'Jellyfin',
    primary: Color(0xFFAA5CC3),
    secondary: Color(0xFF2B7FFF),
    backgroundTop: Color(0xFF0B1030),
    backgroundBottom: Color(0xFF1A2568),
    sidebarBackground: Color(0xFF0A0E24),
    accent: Color(0xFF2B7FFF),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    sidebarLogo: 'assets/images/Logo_letter_fynitiv.png',
    sidebarWidth: 260,
    showContinueRow: true,
    showNewReleasesRow: true,
    cardBorderRadius: 10,
    sidebarCollapsible: true,
    titleMarqueeOnHover: true,
  );

  /// Estilo Disney+ (azul oscuro, acento celeste, textos claros).
  static const Skin disneyPlus = Skin(
    id: 'disney_plus',
    name: 'Disney+',
    primary: Color(0xFF0B1030),
    secondary: Color(0xFF1A2568),
    backgroundTop: Color(0xFF05080F),
    backgroundBottom: Color(0xFF0B1030),
    sidebarBackground: Color(0xFF03060B),
    accent: Color(0xFF00A0D1),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    sidebarLogo: 'assets/images/Logo_letter_fynitiv.png',
    logoPosition: LogoPosition.bottom,
    avatarPosition: LogoPosition.top,
    bannerShowTitle: false,
    sidebarWidth: 260,
    sidebarHeaderSpacing: 24,
    navItemIconSpacing: 24,
    showContinueRow: true,
    showNewReleasesRow: true,
    showNewReleasesBanner: true,
    bannerBorder: true,
    bannerBorderWidth: 0.05,
    bannerBorderHoverWidth: 4,
    bannerBorderColor: Color.fromARGB(255, 228, 228, 228),
    bannerLogoWidthFactor: 0.35,
    bannerLogoMaxHeight: 130,
    bannerDotAlignment: SliderDotAlignment.center,
    bannerDotsOutside: true,
    bannerShowNewBadge: true,
    bannerInlineMeta: true,
    bannerTransition: SliderTransition.slide,
    bannerHeightFactor: 0.45,
    bannerMaxHeight: 520,
    bannerHorizontalPadding: 20,
    bannerShadow: true,
    bannerHoverScale: 1.0,
    bannerVignette: true,
    bannerVignetteMode: SliderVignetteMode.left,
    bannerVignetteSize: 620,
    bannerVignetteOpacity: 1,
    homeCardScale: 2,
    rowSpacing: 40,
    cardBorderRadius: 6,
    bannerBorderRadius: 16,
    sidebarCollapsible: true,
    itemSpacing: 20,
    homeLayout: [
      HomeSection.featuredSlider(),
      HomeSection.continueWatching(
        HomeScroll(
          titleKey: HomeScrollTitle.continueWatching,
          genres: [],
          imageSource: RowImageSource.backdrop,
          cardType: HomeScrollCardType.backdrop,
        ),
      ),
      HomeSection.newReleases(),
      HomeSection.custom(
        HomeScroll(
          titleKey: HomeScrollTitle.actionMovies,
          genres: [JellyGenre.action],
          bottomVignette: true,
          bottomVignetteHeight: 70,
          bottomVignetteOpacity: 0.8,
          cardType: HomeScrollCardType.backdrop,
          imageSource: RowImageSource.backdrop,
          showLogo: true,
          logoPosition: RowLogoPosition.bottom,
        ),
      ),
      HomeSection.custom(
        HomeScroll(
          titleKey: HomeScrollTitle.familyMovies,
          genres: [JellyGenre.animation, JellyGenre.family, JellyGenre.kids],
          bottomVignette: true,
          cardType: HomeScrollCardType.backdrop,
          imageSource: RowImageSource.backdrop,
        ),
      ),
      HomeSection.recent(),
      HomeSection.nextUp(),
    ],
    vodLayout: [
      VodSection.featuredSlider(),
      VodSection.continueWatching(
        HomeScroll(
          titleKey: HomeScrollTitle.continueWatching,
          genres: [],
          imageSource: RowImageSource.thumb,
          cardType: HomeScrollCardType.backdrop,
          cardBorderRadius: 1,
          tapAction: HomeScrollTapAction.play,
        ),
      ),
      VodSection.nextUp(
        HomeScroll(
          titleKey: HomeScrollTitle.nextUp,
          genres: [],
          imageSource: RowImageSource.thumb,
          cardType: HomeScrollCardType.backdrop,
          cardBorderRadius: 1,
          tapAction: HomeScrollTapAction.play,
        ),
      ),
      VodSection.newReleases(
        HomeScroll(
          titleKey: HomeScrollTitle.newReleases,
          genres: [],
          showSeeMore: false,
          showHoverOverlay: false,
          sort: HomeScrollSort.added,
          metaOverlay: true,
          bottomVignette: true,
          bottomVignetteHeight: 200,
          bottomVignetteOpacity: 0.8,
          metaAlignment: RowMetaAlign.center,
          cardType: HomeScrollCardType.poster,
          imageSource: RowImageSource.backdrop,
          logoPosition: RowLogoPosition.bottom,
          showLogo: true,
          logoSize: 66,
          tapAction: HomeScrollTapAction.details,
        ),
      ),
      // Una entrada por biblioteca, cada una con su propia imagen y layout:
      // Películas en backdrop panorámico, Series en póster vertical.
      VodSection.library(
        HomeScroll(
          titleKey: HomeScrollTitle.library,
          genres: [],
          cardType: HomeScrollCardType.poster,
          imageSource: RowImageSource.primary,
          showSeeMore: false,
          showHoverOverlay: false,
          sort: HomeScrollSort.random,
          hideTitle: true,
          hideYear: true,
          tapAction: HomeScrollTapAction.details,
        ),
        {CollectionType.movies},
      ),
      VodSection.library(
        HomeScroll(
          titleKey: HomeScrollTitle.library,
          genres: [],
          cardType: HomeScrollCardType.poster,
          imageSource: RowImageSource.primary,
          showSeeMore: false,
          showHoverOverlay: false,
          sort: HomeScrollSort.random,
          tapAction: HomeScrollTapAction.details,
          hideTitle: true,
          hideYear: true,
        ),
        {CollectionType.tvshows},
      ),
      VodSection.custom(
        HomeScroll(
          titleKey: HomeScrollTitle.actionMovies,
          types: [BaseItemKind.movie],
          genres: [JellyGenre.action],
          cardType: HomeScrollCardType.poster,
          imageSource: RowImageSource.primary,
          hideTitle: true,
          hideYear: true,
          showHoverOverlay: false,
          hoverScale: 1.04,
          showSeeMore: false,
          sort: HomeScrollSort.random,
          tapAction: HomeScrollTapAction.details,
        ),
      ),
      VodSection.custom(
        HomeScroll(
          titleKey: HomeScrollTitle.animationMovies,
          types: [BaseItemKind.movie],
          genres: [JellyGenre.animation],
          cardType: HomeScrollCardType.poster,
          imageSource: RowImageSource.primary,
          hideTitle: true,
          hideYear: true,
          showHoverOverlay: false,
          hoverScale: 1.04,
          showSeeMore: false,
          sort: HomeScrollSort.random,
          tapAction: HomeScrollTapAction.details,
        ),
      ),
      VodSection.custom(
        HomeScroll(
          titleKey: HomeScrollTitle.crime,
          types: [BaseItemKind.movie],
          genres: [JellyGenre.crime],
          cardType: HomeScrollCardType.poster,
          imageSource: RowImageSource.primary,
          hideTitle: true,
          hideYear: true,
          showHoverOverlay: false,
          hoverScale: 1.04,
          showSeeMore: false,
          sort: HomeScrollSort.random,
          tapAction: HomeScrollTapAction.details,
        ),
      ),
    ],
  );

  /// Estilo Amazon Prime (azul oscuro casi negro, acento celeste "Prime").
  static const Skin amazonPrime = Skin(
    id: 'amazon_prime',
    name: 'Prime',
    primary: Color(0xFF00A8E1),
    secondary: Color(0xFF232F3E),
    backgroundTop: Color(0xFF0A0F14),
    backgroundBottom: Color(0xFF121A24),
    sidebarBackground: Color(0xFF070B0F),
    accent: Color(0xFF00A8E1),
    textPrimary: Colors.white,
    textSecondary: Color(0xB3FFFFFF),
    sidebarLogo: 'assets/images/Logo_letter_fynitiv.png',
    sidebarPosition: SidebarPosition.top,
    sidebarSelectedColor: Color(0xFF6B6B6B),
    sidebarWidth: 240,
    showContinueRow: true,
    cardImageType: CardImageType.backdrop,
    cardLogo: 'assets/images/jellyfin.png',
    cardLogoSize: 24,
    playerLogo: 'assets/images/jellyfin.png',
    showNewReleasesRow: true,
    showNewReleasesBanner: true,
    bannerLogoWidthFactor: 0.60,
    bannerShowArrows: true,
    bannerDotAlignment: SliderDotAlignment.center,
    bannerShowIncludedBadge: true,
    bannerShowJellyfinLogo: true,
    bannerHoverReveal: true,
    bannerShowActions: true,
    showTrailerInSlider: true,
    bannerTransition: SliderTransition.fade,
    bannerArrowsOnHover: true,
    bannerShowTitle: false,
    bannerAttachedTop: true,
    bannerShowAgeRating: true,
    bannerContentScale: 1.2,
    bannerHeightFactor: 0.5,
    bannerMaxHeight: 580,
    bannerVignette: true,
    bannerBorderWidth: 1.5,
    bannerBorderHoverWidth: 2.5,
    bannerBorderColor: Color(0xFFFFFFFF),
    homeCardWidth: 350,
    homeRowHeight: 340,
    rowSpacing: 50,
    cardBorderRadius: 4,
    sidebarCollapsible: true,
    cardHoverExtension: true,
    topBarFloating: false,
    showCardBadge: true,
    homeScrolls: [
      HomeScroll(
        titleKey: HomeScrollTitle.actionMovies,
        genres: [JellyGenre.action],
        cardType: HomeScrollCardType.backdrop,
      ),
      HomeScroll(
        titleKey: HomeScrollTitle.familyMovies,
        genres: [JellyGenre.animation, JellyGenre.family, JellyGenre.kids],
        cardType: HomeScrollCardType.backdrop,
      ),
    ],
  );

  /// Estilo Movistar+ (oscuro, acento naranja/rojo).
  static const Skin movistarPlus = Skin(
    id: 'movistar_plus',
    name: 'Movistar+',
    primary: Color(0xFFFF6F00),
    secondary: Color(0xFF1B1B2F),
    backgroundTop: Color(0xFF0E0E1A),
    backgroundBottom: Color(0xFF1B1B2F),
    sidebarBackground: Color(0xFF0A0A14),
    accent: Color(0xFFFF6F00),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xB3FFFFFF),
    sidebarLogo: 'assets/images/Logo_letter_fynitiv.png',
    sidebarWidth: 260,
    showContinueRow: true,
    showNewReleasesRow: true,
    cardBorderRadius: 8,
    sidebarCollapsible: true,
  );

  static const List<Skin> all = [
    jellyfinDefault,
    disneyPlus,
    amazonPrime,
    movistarPlus,
  ];
}
